import localFont from "next/font/local";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import connectDB from "@/libs/mongoose";
import MongoDBStatus from "@/components/MongoDBStatus";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let isConnected = false;

  try {
    await connectDB();
    isConnected = true;
  } catch (error) {
    console.error("MongoDB connection error:", error);
    isConnected = false;
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="bottom-center" />
        <MongoDBStatus isConnected={isConnected} />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
